singleton Material("etki.skin.sb_rush")
{
    mapTo = "etki.skin.sb_rush";
    overlayMap[2] = "vehicles/etki/spaceballs_skins/etki_skin_rush.dds";
    diffuseMap[2] = "vehicles/etki/etki_c_alt.dds";
    specularMap[2] = "vehicles/etki/etki_s.dds";
    normalMap[2] = "vehicles/etki/etki_n.dds";
    diffuseMap[1] = "vehicles/etki/etki_d_alt.dds";
    specularMap[1] = "vehicles/etki/etki_s.dds";
    normalMap[1] = "vehicles/etki/etki_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/etki/etki_s.dds";
    normalMap[0] = "vehicles/etki/etki_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("etki_modparts.skin.sb_rush")
{
    mapTo = "etki_modparts.skin.sb_rush";
    overlayMap[2] = "vehicles/etki/spaceballs_skins/etki_skin_rush.dds";
    diffuseMap[2] = "vehicles/etki/etki_modparts_c.dds";
    specularMap[2] = "vehicles/etki/etki_modparts_s.dds";
    normalMap[2] = "vehicles/etki/etki_modparts_n.dds";
    diffuseMap[1] = "vehicles/etki/etki_modparts_d.dds";
    specularMap[1] = "vehicles/etki/etki_modparts_s.dds";
    normalMap[1] = "vehicles/etki/etki_modparts_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/etki/etki_modparts_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("etki.skin.sb_valor")
{
    mapTo = "etki.skin.sb_valor";
    overlayMap[2] = "vehicles/etki/spaceballs_skins/etki_skin_valor.dds";
    diffuseMap[2] = "vehicles/etki/etki_c_alt.dds";
    specularMap[2] = "vehicles/etki/etki_s.dds";
    normalMap[2] = "vehicles/etki/etki_n.dds";
    diffuseMap[1] = "vehicles/etki/etki_d_alt.dds";
    specularMap[1] = "vehicles/etki/etki_s.dds";
    normalMap[1] = "vehicles/etki/etki_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/etki/etki_s.dds";
    normalMap[0] = "vehicles/etki/etki_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("etki_modparts.skin.sb_valor")
{
    mapTo = "etki_modparts.skin.sb_valor";
    overlayMap[2] = "vehicles/etki/spaceballs_skins/etki_skin_valor.dds";
    diffuseMap[2] = "vehicles/etki/etki_modparts_c.dds";
    specularMap[2] = "vehicles/etki/etki_modparts_s.dds";
    normalMap[2] = "vehicles/etki/etki_modparts_n.dds";
    diffuseMap[1] = "vehicles/etki/etki_modparts_d.dds";
    specularMap[1] = "vehicles/etki/etki_modparts_s.dds";
    normalMap[1] = "vehicles/etki/etki_modparts_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/etki/etki_modparts_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("etki.skin.sb_mystic")
{
    mapTo = "etki.skin.sb_mystic";
    overlayMap[2] = "vehicles/etki/spaceballs_skins/etki_skin_mystic.dds";
    diffuseMap[2] = "vehicles/etki/etki_c_alt.dds";
    specularMap[2] = "vehicles/etki/etki_s.dds";
    normalMap[2] = "vehicles/etki/etki_n.dds";
    diffuseMap[1] = "vehicles/etki/etki_d_alt.dds";
    specularMap[1] = "vehicles/etki/etki_s.dds";
    normalMap[1] = "vehicles/etki/etki_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/etki/etki_s.dds";
    normalMap[0] = "vehicles/etki/etki_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("etki_modparts.skin.sb_mystic")
{
    mapTo = "etki_modparts.skin.sb_mystic";
    overlayMap[2] = "vehicles/etki/spaceballs_skins/etki_skin_mystic.dds";
    diffuseMap[2] = "vehicles/etki/etki_modparts_c.dds";
    specularMap[2] = "vehicles/etki/etki_modparts_s.dds";
    normalMap[2] = "vehicles/etki/etki_modparts_n.dds";
    diffuseMap[1] = "vehicles/etki/etki_modparts_d.dds";
    specularMap[1] = "vehicles/etki/etki_modparts_s.dds";
    normalMap[1] = "vehicles/etki/etki_modparts_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/etki/etki_modparts_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("etki.skin.sb_instinct")
{
    mapTo = "etki.skin.sb_instinct";
    overlayMap[2] = "vehicles/etki/spaceballs_skins/etki_skin_instinct.dds";
    diffuseMap[2] = "vehicles/etki/etki_c_alt.dds";
    specularMap[2] = "vehicles/etki/etki_s.dds";
    normalMap[2] = "vehicles/etki/etki_n.dds";
    diffuseMap[1] = "vehicles/etki/etki_d_alt.dds";
    specularMap[1] = "vehicles/etki/etki_s.dds";
    normalMap[1] = "vehicles/etki/etki_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/etki/etki_s.dds";
    normalMap[0] = "vehicles/etki/etki_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("etki_modparts.skin.sb_instinct")
{
    mapTo = "etki_modparts.skin.sb_instinct";
    overlayMap[2] = "vehicles/etki/spaceballs_skins/etki_skin_instinct.dds";
    diffuseMap[2] = "vehicles/etki/etki_modparts_c.dds";
    specularMap[2] = "vehicles/etki/etki_modparts_s.dds";
    normalMap[2] = "vehicles/etki/etki_modparts_n.dds";
    diffuseMap[1] = "vehicles/etki/etki_modparts_d.dds";
    specularMap[1] = "vehicles/etki/etki_modparts_s.dds";
    normalMap[1] = "vehicles/etki/etki_modparts_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/etki/etki_modparts_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};
